### ISSUE TITLE
TyperError when trying to read Global Precipitation Mission Radar Data in H5 files

### ISSUE THREAD

**Issue by winash12** [wradlib/wradlib#273]
I am trying to read GPM radar data that has .h5 extensions with wradlib 1.0.0 and numpy 1.14.5 and python 3.6 and I am getting the following  error below . 

The code in wradlib that causes this problem is [https://github.com/wradlib/wradlib/blob/03b09b61afcce0c7bfa5e437a4b1fc3dcaa60b44/wradlib/io/hdf.py#L471](url)

 `mask = np.nonzero(np.count_nonzero(mask, axis=1))`

> 

Traceback (most recent call last):
  File "sr_offset_correction.py", line 232, in <module>
    main()
  File "sr_offset_correction.py", line 42, in main
    sr_data = wrl.io.read_gpm(gpm_file,None)
  File "/usr/local/lib/python3.6/dist-packages/wradlib-1.0.0-py3.6.egg/wradlib/io/hdf.py", line 473, in read_gpm
  File "/usr/local/lib/python3.6/dist-packages/numpy-1.14.5-py3.6-linux-x86_64.egg/numpy/core/numeric.py", line 419, in count_nonzero
    a_bool = a.astype(np.bool_, copy=False)
TypeError: astype() got an unexpected keyword argument 'copy'

**Comment by kmuehlbauer** [comment]
@winash12 Thanks for reporting this. As discussed on gitter, PR welcome.
